# Generated by Django 5.1 on 2026-03-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='generated_cv_path',
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_type', models.CharField(choices=[('general', 'General CV'), ('job_specific', 'Job-Specific CV')], default='general', max_length=20)),
                ('generated_pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_text_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailored_cvs', to='jobs.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'unique_together': {('profile', 'job', 'cv_type')},
            },
        ),
    ]
