# Generated by Django 5.1 on 2026-03-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_generated_cv_path_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='generated_text_content',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='cv',
            name='generated_json_content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
