# Generated by Django 5.1 on 2026-03-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
