# Generated by Django 5.1 on 2026-03-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
