# Generated by Django 5.1 on 2026-03-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_verified',
        ),
    ]
